[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "none"
opacity = 0.92
blur = true

[font]
size = 8.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
offset = { x = 0, y = 1 }
glyph_offset = { x = 0, y = 1 }

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = "Block"

# falcon colorscheme for alacritty
[colors.primary]
background = "#2e3440"
foreground = "#d8dee9"
dim_foreground = "#a5abb6"

[colors.cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.vi_mode_cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.selection]
text = "CellForeground"
background = "#4c566a"

[colors.search.matches]
foreground = "CellBackground"
background = "#88c0d0"

[colors.search.bar]
background = "#434c5e"
foreground = "#d8dee9"

[colors.normal]
black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"

[colors.bright]
black = "#4c566a"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#eceff4"

[colors.dim]
black = "#373e4d"
red = "#94545d"
green = "#809575"
yellow = "#b29e75"
blue = "#68809a"
magenta = "#8c738c"
cyan = "#6d96a5"
white = "#aeb3bb"

[selection]
save_to_clipboard = true

[debug]
log_level = "Warn"

[[keyboard.bindings]]
key = "C"
mods = "Super|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Super|Shift"
action = "Paste"
